apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: skelloapp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: skelloapp
  source:
    # repoURL: https://github.com/skelloapp/skello-app
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
