apiVersion: apps/v1
kind: Deployment
metadata:
  name: skellapp
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: skelloapp
  template:
    metadata:
      labels:
        app: skelloapp
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
        name: guestbook-ui
        ports:
        - containerPort: 80
