apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: skellapp
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: skelloApp project for reviewapps

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - 'https://github.com/argoproj/argocd-example-apps'

  # Only permit applications to deploy to the guestbook namespace in the same cluster
  # Destination clusters can be identified by 'server', 'name', or both.
  destinations:
  - namespace: default
    server: https://kubernetes.default.svc
    name: in-cluster