apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: argo-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/guillaumestreitmatter/sample-argocd
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-demo
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
