apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: svccommunications
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: svccommunications
  source:
    repoURL: https://github.com/skelloapp/svc-communications
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
